## Parte 1: Numpy:
Para los ejercicios siguiente genere el código que considere para resolver el problema que se le plantea.

In [44]:
# Celda para almacenar los imports
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [4]:
bool_array = [True] * 1000
size = sys.getsizeof(bool_array)
print("El tamaño del array de booleanos es:", size, "bytes")

El tamaño del array de booleanos es: 8056 bytes


2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [5]:
pares = [i for i in range(100, 0, -2)]
ultimos_10 = pares[-10:]
print("Los últimos 10 números pares son:", ultimos_10)

Los últimos 10 números pares son: [20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


3. Dado el array
                    [[2 4 5 6],
                    [0 3 7 4],
                    [8 8 5 2],
                    [1 5 6 1]]
Seleccione con una instrucción el subarray de elementos
                    [0 3 7 4]
Después, seleccione el subarray de elementos
                      [[2 5],
                      [8 5]]

In [9]:
arr = np.array([[2, 4, 5, 6],
                [0, 3, 7, 4],
                [8, 8, 5, 2],
                [1, 5, 6, 1]])

sub_1 = arr[1]
print("El subarray seleccionado es:", sub_1)
sub_2 = arr[:2, [0, 2]]
print("El subarray seleccionado es:", sub_2)

El subarray seleccionado es: [0 3 7 4]
El subarray seleccionado es: [[2 5]
 [0 7]]


4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [10]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

diferencia = a - b
media = np.mean(diferencia)

print("La media aritmética de la diferencia (a-b) es:", media)

La media aritmética de la diferencia (a-b) es: -0.25


5. Tengo valores de cordenadas (x, y) en las columnas del array:
[[1.33, 4.5],
[30.0, 10.7],
[70.2, 0.5]]
<br>
Agregue a este array las coordenadas (37.1, -3.6). Muestre en pantalla las dimensiones del nuevo array.

In [11]:
coord = np.array([[1.33, 4.5],
                [30.0, 10.7],
                [70.2, 0.5]])

nueva_fila = np.array([37.1, -3.6])
coord_nuevas = np.append(coord, [nueva_fila], axis=0)

print("Las dimensiones del nuevo array son:", coord_nuevas.shape)

Las dimensiones del nuevo array son: (4, 2)


6. Copie el array del ejercicio anterior. Traspóngalo. Agregue ahora dos nuevos pares de coordenadas: (10.8, 3.0) y (35.8, 12.0).

In [12]:
coord_t = coord_nuevas.T
print("Array transpuesto:\n", coord_t)

nuevas_filas = np.array([[10.8, 3.0],
                         [35.8, 12.0]])

coord_t_nuevo = np.append(coord_t, nuevas_filas.T, axis=1)
print("Array transpuesto con nuevas filas:\n", coord_t_nuevo)

Array transpuesto:
 [[ 1.33 30.   70.2  37.1 ]
 [ 4.5  10.7   0.5  -3.6 ]]
Array transpuesto con nuevas filas:
 [[ 1.33 30.   70.2  37.1  10.8  35.8 ]
 [ 4.5  10.7   0.5  -3.6   3.   12.  ]]


## Parte 2: Exploración y Minería de Datos
Con el dataset nucleospoblacion.csv adjunto al laboratorio, luego responda las siguientes preguntas usando pandas y matplotlib.

1. ¿Cuántos Municipios tienen más de 100000 habitantes?

In [14]:
# Se cargan los datos del archivo CSV en un DataFrame de pandas
df = pd.read_csv("data/NucleosPoblacion.csv")

# Se seleccionan los municipios con más de 100000 habitantes y contarlos
num_municipios = len(df[df["Poblacion"] > 100000]["Municipio"].unique())

print(f"Hay {num_municipios} municipios con más de 100000 habitantes.")

Hay 62 municipios con más de 100000 habitantes.


2. Realice una gráfica de barras sobre la población de cada Municipio, ordenela de menor a mayo y responda: <br>
    a. ¿Cuál es la segunda ciudad más poblada?<br>
    b. ¿Qué posición ocupa Granada en el ranking de las ciudades más pobladas?

In [ ]:
# Se ordenan los datos por población de menor a mayor
df_orden = df.sort_values("Poblacion")
# Se crea la gráfica de barras
plt.barh(df_orden["Municipio"], df_orden["Poblacion"])
plt.xlabel("Población")
plt.show()

In [21]:
# a. Identificar la segunda ciudad más poblada
segunda_ciudad = df_orden.iloc[-2]["Municipio"]
print(f"La segunda ciudad más poblada es {segunda_ciudad}.")

# b. Identificar la posición de Granada en el ranking
posicion_granada = df_orden[df_orden["Municipio"] == "Granada"].index.item() + 1
print(f"Granada ocupa la posición número {posicion_granada} en el ranking de ciudades más pobladas.")

La segunda ciudad más poblada es Barcelona.
Granada ocupa la posición número 273 en el ranking de ciudades más pobladas.


3. ¿Cuántos municipios de Extremadura tienen más de 5000 habitantes?.

In [34]:
municipios_extremadura = df[df['Provincia'] == 'Extremadura']
num_municipios_mas_5000 = len(municipios_extremadura[municipios_extremadura['Poblacion'] > 5000])

print("El número de municipios en Extremadura con más de 5000 habitantes es:", num_municipios_mas_5000)

El número de municipios en Extremadura con más de 5000 habitantes es: 0


4. ¿Cuál es el municipio situado más al Norte? (Usar el valor de la coordenada "Y" que representa la latitud en grados). Proporcione también la provincia a la que pertenece y su población.

In [37]:
municipio_norte = df.loc[df['Y'].idxmax()]

print(f"El municipio más al norte es {municipio_norte['Municipio']}, en la provincia de {municipio_norte['Provincia']}, con una población de {municipio_norte['Poblacion']} habitantes.")

El municipio más al norte es Viveiro, en la provincia de Lugo, con una población de 16211.0 habitantes.


5. Obtenga la media, mediana, desviación estándar, valor máximo y valor mínimo de la población de los municipios
de la provincia de Granada.

In [40]:
# Se filtran los municipios de Granada
df_granada = df.loc[df['Provincia'] == 'Granada']

# Se obtienen las estadísticas de la población
estadisticas_poblacion = df_granada['Poblacion'].describe()

print(f"Estadísticas de la población de los municipios de Granada:\n {estadisticas_poblacion}")

Estadísticas de la población de los municipios de Granada:
 count        20.000000
mean      30217.850000
std       50355.491715
min       10386.000000
25%       13146.500000
50%       17526.000000
75%       21739.750000
max      239154.000000
Name: Poblacion, dtype: float64


6. Realice un histograma con la población de los Municipios para cada una de las provincias.

In [ ]:
# Se crean los histogramas
df.hist(column='Poblacion', by='Provincia', bins=20, figsize=(10, 8))

plt.show()

7. Seleccione al azar cincuenta municipios diferentes de entre los diponibles en el archivo. Asegúrese de que no se repitan. ¿Luego calcule el promedio de la población y la desviación estándar de esto 50 municipios?

In [46]:
# Se cargan los municipios en una lista
municipios = df['Municipio'].unique().tolist()
# Se genera una muestra al azar de numeros
muestra = random.sample(municipios, 50)
# Se seleccionan los 50 municipios al azar
muestra_data = df[df['Municipio'].isin(muestra)]

poblacion_mean = muestra_data['Poblacion'].mean()
poblacion_std = muestra_data['Poblacion'].std()

print(f"Promedio de población de los 50 municipios seleccionados: {round(poblacion_mean, 2)}")
print(f"Desviación estándar de la población de los 50 municipios seleccionados: {round(poblacion_std, 2)}")

Promedio de población de los 50 municipios seleccionados: 33233.79
Desviación estándar de la población de los 50 municipios seleccionados: 37122.97


8. Dígame los nombres de los Municipios más cercano y más
lejano a Madrid. Para ello debe calcular la distancia en
todos ellos y Madrid. No considere a Madrid en el
análisis ya que la distancia sería cero.

In [56]:
# Se obtienen las coordenadas de Madrid
madrid_latitud = df[df['Municipio'] == 'Madrid']['X'].values[0]
madrid_longitud = df[df['Municipio'] == 'Madrid']['Y'].values[0]

# Se filtran los municipios que no sean Madrid
df_municipios_ntmadrid = df[df['Municipio'] != 'Madrid']

In [57]:
# Se calcula la distancia entre Madrid y cada municipio
distancias = np.sqrt((df_municipios_ntmadrid['Y'] - madrid_latitud)**2 + (df_municipios_ntmadrid['X'] - madrid_longitud)**2)

# Se encuentra el índice del municipio más cercano y más lejano
indice_municipio_mas_cercano = distancias.idxmin()
indice_municipio_mas_lejano = distancias.idxmax()

# Se obtiene el nombre de los municipios más cercano y más lejano
nombre_municipio_mas_cercano = df_municipios_ntmadrid.loc[indice_municipio_mas_cercano, 'Municipio']
nombre_municipio_mas_lejano = df_municipios_ntmadrid.loc[indice_municipio_mas_lejano, 'Municipio']

print("El municipio más cercano a Madrid es:", nombre_municipio_mas_cercano)
print("El municipio más lejano a Madrid es:", nombre_municipio_mas_lejano)

El municipio más cercano a Madrid es: Maó
El municipio más lejano a Madrid es: Carballo
