## Parte 1: Numpy:
Para los ejercicios siguiente genere el código que considere para resolver el problema que se le plantea.

In [6]:
# Celda para almacenar los imports
import sys
import numpy as np

1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [4]:
bool_array = [True] * 1000
size = sys.getsizeof(bool_array)
print("El tamaño del array de booleanos es:", size, "bytes")

El tamaño del array de booleanos es: 8056 bytes


2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [5]:
pares = [i for i in range(100, 0, -2)]
ultimos_10 = pares[-10:]
print("Los últimos 10 números pares son:", ultimos_10)

Los últimos 10 números pares son: [20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


3. Dado el array
                    [[2 4 5 6],
                    [0 3 7 4],
                    [8 8 5 2],
                    [1 5 6 1]]
Seleccione con una instrucción el subarray de elementos
                    [0 3 7 4]
Después, seleccione el subarray de elementos
                      [[2 5],
                      [8 5]]

In [9]:
arr = np.array([[2, 4, 5, 6],
                [0, 3, 7, 4],
                [8, 8, 5, 2],
                [1, 5, 6, 1]])

sub_1 = arr[1]
print("El subarray seleccionado es:", sub_1)
sub_2 = arr[:2, [0, 2]]
print("El subarray seleccionado es:", sub_2)

El subarray seleccionado es: [0 3 7 4]
El subarray seleccionado es: [[2 5]
 [0 7]]


4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [10]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

diferencia = a - b
media = np.mean(diferencia)

print("La media aritmética de la diferencia (a-b) es:", media)

La media aritmética de la diferencia (a-b) es: -0.25


5. Tengo valores de cordenadas (x, y) en las columnas del array:
[[1.33, 4.5],
[30.0, 10.7],
[70.2, 0.5]]
<br>
Agregue a este array las coordenadas (37.1, -3.6). Muestre en pantalla las dimensiones del nuevo array.

In [11]:
coord = np.array([[1.33, 4.5],
                [30.0, 10.7],
                [70.2, 0.5]])

nueva_fila = np.array([37.1, -3.6])
coord_nuevas = np.append(coord, [nueva_fila], axis=0)

print("Las dimensiones del nuevo array son:", coord_nuevas.shape)

Las dimensiones del nuevo array son: (4, 2)


6. Copie el array del ejercicio anterior. Traspóngalo. Agregue ahora dos nuevos pares de coordenadas: (10.8, 3.0) y (35.8, 12.0).

In [12]:
coord_t = coord_nuevas.T
print("Array transpuesto:\n", coord_t)

nuevas_filas = np.array([[10.8, 3.0],
                         [35.8, 12.0]])

coord_t_nuevo = np.append(coord_t, nuevas_filas.T, axis=1)
print("Array transpuesto con nuevas filas:\n", coord_t_nuevo)

Array transpuesto:
 [[ 1.33 30.   70.2  37.1 ]
 [ 4.5  10.7   0.5  -3.6 ]]
Array transpuesto con nuevas filas:
 [[ 1.33 30.   70.2  37.1  10.8  35.8 ]
 [ 4.5  10.7   0.5  -3.6   3.   12.  ]]
